### ISSUE TITLE
Error when i run yarn dev

### ISSUE THREAD

**Issue by Jkudjo** [Cveinnt/LiveTerm#16]
$ next dev
/root/LiveTerm/node_modules/react-dom/cjs/react-dom-server.browser.development.js:145
var textEncoder = new TextEncoder();
                  ^

ReferenceError: TextEncoder is not defined
    at /root/LiveTerm/node_modules/react-dom/cjs/react-dom-server.browser.development.js:145:19
    at Object.<anonymous> (/root/LiveTerm/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6733:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/LiveTerm/node_modules/react-dom/server.browser.js:9:7)

**Comment by Cveinnt** [comment]
hi @Jkudjo, can you verify that your node.js install is up-to-date with `node -v`?

**Comment by Jkudjo** [comment]
node --version
v16.15.0

**Comment by Cveinnt** [comment]
This looks like a node version issue - you can find related discussion [here](https://github.com/jsdom/whatwg-url/issues/209), and specifically [this comment](https://github.com/Automattic/mongoose/issues/10713#issuecomment-921373677). Let me know if this applies to your situation!
